version: '3'
services:
  ui:
    image: docker-react:latest
    container_name: docker-react
    hostname: docker-react
    restart: unless-stopped
    environment:
      - REACT_APP_AWS_REGION=ap-southeast-2
      - REACT_APP_AWS_COGNITO_CLIENT_ID=aaaaabbbbbcccccddddd
      - REACT_APP_AWS_COGNITO_USER_POOL_ID=ap-southeast-2_1234asdc
      - REACT_APP_BASEURL=connectivity.systems
    ports:
      - 3000:3000