version: '3'
services:
  ui:
    image: docker-react:latest
    container_name: docker-react
    hostname: docker-react
    restart: unless-stopped
    environment:
      - AWS_REGION=ap-southeast-2
      - AWS_COGNITO_CLIENT_ID=aaaaabbbbbcccccddddd
      - AWS_COGNITO_USER_POOL_ID=ap-southeast-2_1234asdc
      - BASEURL=connectivity.systems
    ports:
      - 3000:80